name: Netlify Preview Deploy

on:
  pull_request:
    branches: [master]

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - run: npm install netlify-cli -g
    - run: npm ci
    - run: npm run lerna -- bootstrap
    - run: npm run lerna run build
    - run: cd website && cp -R build/. ../dist
    - run: echo "short_sha=${GITHUB_SHA:0:8} >> $GITHUB_ENV"
    - run: npx netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --json --alias="${{ short_sha }}"
    # - run: echo "NETLIFY_RESPONSE=$(npx netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --json --alias=$GITHUB_REF)" >> $GITHUB_ENV
    # - run: echo "NETLIFY_DEPLOY_URL=$(echo ${{ env.NETLIFY_RESPONSE }} | jq -r .deploy_url netlify.json)" >> $GITHUB_ENV
    # - run: echo "NETLIFY_DEPLOY_LOGS=$(echo ${{ env.NETLIFY_RESPONSE }} | jq -r .logs netlify.json)" >> $GITHUB_ENV
    # - run: echo 'NETLIFY_DEPLOY_LOGS=$(jq -r .logs netlify.json)' >> $GITHUB_ENV
    # - run: npm run build-docs
    # - run: cd dist && touch .nojekyll && echo 'tezostaquito.io' > CNAME
    # - name: Publish generated content to GitHub Pages
    #   uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
    #   with:
    #     dir: dist
    #     branch: gh-pages
    #     token: ${{ secrets.ACCESS_TOKEN }}
      env:
        CI: true
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
    - uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'A new deploy preview is available on Netlify at https://${{ short_sha }}--tezostaquito.netlify.app'
          })
