name: Website Deploy

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      
jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - run: npm install netlify-cli -g
    - run: npm ci
    - run: npm run lerna -- bootstrap
    - run: npm run lerna run build
    - run: cd website && cp -R build/. ../dist
    - run: npx netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --json --alias="github-test"
    # - run: npm run build-docs
    # - run: cd dist && touch .nojekyll && echo 'tezostaquito.io' > CNAME
    # - name: Publish generated content to GitHub Pages
    #   uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
    #   with:
    #     dir: dist
    #     branch: gh-pages
    #     token: ${{ secrets.ACCESS_TOKEN }}
      env:
        CI: true
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
    - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'This is a test comment'
            })
